"""empty message

Revision ID: 049b9082f2ac
Revises: 9ff4ed7e7e1a
Create Date: 2019-04-26 15:14:13.165233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049b9082f2ac'
down_revision = '9ff4ed7e7e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimate')
    # ### end Alembic commands ###
