"""empty message

Revision ID: 2eb89b1334ef
Revises: 
Create Date: 2019-01-04 13:49:05.142070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from database.models import User
from estimator import db

# revision identifiers, used by Alembic.
revision = '2eb89b1334ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    default = User('default')
    db.session.add(default)
    db.session.commit()
    # query to load id 
    default = User.query.first()
    default_id = default.id

    # Not strictly necessary as I am going to rename the table.
    op.rename_table('group', 'old_group')

    op.create_table('estimation_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('INSERT INTO estimation_group (name,user) SELECT name, {} FROM old_group'.format(default_id))

    op.drop_table('old_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Insert rows from the older version of the table
    op.execute('INSERT INTO "group" (name) SELECT name FROM estimation_group')

    op.drop_table('estimation_group')
    op.drop_table('user')
    # ### end Alembic commands ###
