"""empty message

Revision ID: 5cb792e653b2
Revises: 049b9082f2ac
Create Date: 2019-07-06 18:56:22.525794

"""
from alembic import op
import sqlalchemy as sa
from estimator import db
from database.models import User

# revision identifiers, used by Alembic.
revision = '5cb792e653b2'
down_revision = '049b9082f2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # set a default passowrd for all rows
    for user in User.query.all():
    	user.email = f'{user.nickname}@test.com'
    	user.password = 'password'
    	db.session.add(user)
    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
