"""empty message

Revision ID: 9ff4ed7e7e1a
Revises: c9c55e3480e0
Create Date: 2019-04-26 07:52:23.331760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff4ed7e7e1a'
down_revision = 'c9c55e3480e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_ref', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('final_estimate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['estimation_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue')
    # ### end Alembic commands ###
